site_name: Template Documentation

# Theme configuration
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs        # Horizontal navigation
    - navigation.sections    # Render sections as groups in sidebar
    - navigation.expand      # Expand all collapsible sections
    - navigation.top         # Back-to-top button
    - navigation.indexes     # Attach section pages to sections
    - toc.integrate
    - content.tabs.link     # Link content tabs
    - content.action.edit    # Edit button
    - content.code.copy     # Add copy button to code blocks
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra_css:
  # Minimal styling - only preserve dark blue header and persistent buttons
  - stylesheets/consolidated/minimal-header.css
  - stylesheets/consolidated/search-dropdown-fix.css
  - stylesheets/persistent-buttons.css
  - stylesheets/video-gallery.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/persistent-buttons.js
  - javascripts/dynamic-navigation.js
  - javascripts/video-data.js
  - javascripts/video-gallery.js

# Persistent buttons configuration
extra:
  persistent_buttons:
    portal_url: 'https://example.com/portal'  # Change this to your actual portal URL
    portal_text: 'Portal'                     # Change this text if needed
    feedback_enabled: true                    # Set to false to disable feedback button
    portal_enabled: true                      # Set to false to disable portal button
    buttons_hideable: true                    # Set to false to prevent hiding buttons

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages

# Site configuration
site_description: Template documentation site with dynamic navigation
site_author: User
site_url: https://example.com/template/

# Repository (commented out to remove GitHub icon)
repo_name: Python Repo
repo_url: https://github.com/username/repo
# edit_uri: edit/main/template/docs/

# Enable edit button
feature:
  content.action.edit: true

# Navigation structure - MODIFY THIS SECTION FOR EACH PROJECT
nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - User Guide:
      - Basic Usage: user-guide/basic-usage.md
      - Advanced Features: user-guide/advanced-features.md
      - Troubleshooting: user-guide/troubleshooting.md
  - Resources:
      - Video Gallery: resources/video-gallery.md
  - API Reference:
      - Overview: api-reference/overview.md
      - Endpoints: api-reference/endpoints.md
      - Authentication: api-reference/authentication.md
  - Help:
      - FAQ: help/faq.md
      - Contact: help/contact.md
      - Email: help/email.md
